# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-21 04:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Build',
            fields=[
                ('session_id', models.IntegerField(primary_key=True, serialize=False)),
                ('started_by', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField()),
                ('summary_status', models.CharField(max_length=100)),
                ('duration', models.FloatField()),
                ('worker_time', models.FloatField()),
                ('bundle_time', models.FloatField()),
                ('num_workers', models.IntegerField()),
                ('branch', models.CharField(max_length=100)),
                ('commit_id', models.CharField(max_length=255)),
                ('started_tests_count', models.IntegerField()),
                ('passed_tests_count', models.IntegerField()),
                ('failed_tests_count', models.IntegerField()),
                ('pending_tests_count', models.IntegerField()),
                ('skipped_tests_count', models.IntegerField()),
                ('error_tests_count', models.IntegerField()),
            ],
        ),
    ]
