# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-21 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ci_projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='build',
            name='session_id',
            field=models.IntegerField(db_column='session_id', primary_key=True, serialize=False),
        ),
    ]
