#!/bin/bash

NAME="ci_dashboard"
DIR=/vagrant/ci_dashboard/src
USER=ubuntu
GROUP=ubuntu
WORKERS=3
BIND=unix:/vagrant/ci_dashboard/run/gunicorn.sock
DJANGO_SETTINGS_MODULE=core.settings.prod
DJANGO_WSGI_MODULE=core.wsgi
LOG_LEVEL=error

cd $DIR
source ../venv/bin/activate

export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DIR:$PYTHONPATH

exec ../venv/bin/gunicorn ${DJANGO_WSGI_MODULE}:application \
  --name $NAME \
  --workers $WORKERS \
  --user=$USER \
  --group=$GROUP \
  --bind=$BIND \
  --log-level=$LOG_LEVEL \
  --log-file=/vagrant/ci_dashboard/logs/gunicorn.log
